"use client";

import { useRef, useState } from "react";
import { useAppState } from "@/components/app/AppState";
import { UploadEmptyState } from "@/components/home/UploadEmptyState";
import { Processing } from "@/components/home/Processing";
import { Results } from "@/components/home/Results";
import { DEFAULT_ANALYSIS } from "@/lib/analysis/default";
import type { Analysis } from "@/lib/analysis/types";

/**
 * /home is a small state machine:
 *   not analyzed  → UploadEmptyState (no bottom nav)
 *   processing    → Processing (~2.4s) while the backend analyzes in parallel
 *   analyzed      → Results (bottom nav appears)
 *
 * Every onboarding path hands over a fetcher that resolves to an Analysis.
 * If the backend is unreachable the app falls back to the built-in demo
 * analysis (same shape, generated by the same engine) — the product never
 * dead-ends. Returning users land straight on Results from localStorage.
 */
export default function HomePage() {
  const { analyzed, hydrated, setAnalyzed, setAnalysis } = useAppState();
  const [processing, setProcessing] = useState(false);
  const resultRef = useRef<Analysis | null>(null);
  const pendingRef = useRef<Promise<void> | null>(null);

  const start = (fetcher: () => Promise<Analysis>) => {
    resultRef.current = null;
    pendingRef.current = fetcher()
      .then((a) => {
        resultRef.current = a;
      })
      .catch(() => {
        resultRef.current = DEFAULT_ANALYSIS; // backend down → demo mode
      });
    setProcessing(true);
  };

  const finish = async () => {
    await (pendingRef.current ?? Promise.resolve());
    setAnalysis(resultRef.current ?? DEFAULT_ANALYSIS);
    setProcessing(false);
    setAnalyzed(true);
  };

  // avoid an empty→results flash before localStorage is read
  if (!hydrated) {
    return (
      <div className="fixed inset-0 z-40 flex items-center justify-center bg-base">
        <span className="text-[20px] font-extrabold text-gold">Ants</span>
      </div>
    );
  }

  if (processing) {
    return <Processing onDone={finish} />;
  }

  if (analyzed) {
    return <Results />;
  }

  return <UploadEmptyState onStart={start} />;
}
